sudo: false
language: java
jdk:
- oraclejdk8
services: 
addons:
  postgresql: '9.4'
cache:
  directories:
  - $HOME/.gradle/caches
  - $HOME/.gradle/wrapper
before_script:
- psql --version
- psql -c 'create database test_openregister_java;' -U postgres
- psql -c 'create database ft_openregister_java;' -U postgres
script:
- ./gradlew clean build
