---
food-premises:
  entry-number: "8"
  item-hash: "sha-256:1d1816687f97ed4ec20919feed15db5cbfc2e34aa00376dde1bfdcf849c5f2a9"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Premises which prepare and serve food"
  phase: "alpha"
  fields:
  - "food-premises"
  - "name"
  - "business"
  - "food-premises-types"
  - "local-authority"
  - "premises"
  - "start-date"
  - "end-date"
  register: "food-premises"
  registry: "food-standards-agency"
country:
  entry-number: "3"
  item-hash: "sha-256:81678527d819990783e728469603ee58acade2a899759f5ac125295b6ad36344"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "British English-language names and descriptive terms for countries"
  phase: "alpha"
  fields:
  - "country"
  - "name"
  - "official-name"
  - "citizen-names"
  - "start-date"
  - "end-date"
  register: "country"
  registry: "foreign-commonwealth-office"
registry:
  entry-number: "17"
  item-hash: "sha-256:993cc295319d62e1d0978ce351713163bdb9ae19da2c48afdbcd2f7b2201c057"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Bodies responsible for the maintainance of one or more registers"
  phase: "alpha"
  fields:
  - "registry"
  register: "registry"
  registry: "cabinet-office"
address:
  entry-number: "1"
  item-hash: "sha-256:6a7bcb516b4a465f3340a31ab42a35a9193e512608d9577388da4d99251880a8"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Postal addresses in the UK"
  phase: "alpha"
  fields:
  - "address"
  - "property"
  - "street"
  - "locality"
  - "town"
  - "area"
  - "postcode"
  - "country"
  - "latitude"
  - "longitude"
  register: "address"
  registry: "office-for-national-statistics"
  copyright: "Contains Ordnance Survey data © Crown copyright & database right 2015\n\
    \ Contains Royal Mail data © Royal Mail copyright & database right 2015\n"
postcode:
  entry-number: "13"
  item-hash: "sha-256:bbd8c04498299f15c177783291e531793774f4ec6ba9455b5a0b4920e35cb643"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Postal codes which may appear in a UK address"
  phase: "alpha"
  fields:
  - "postcode"
  - "point"
  register: "postcode"
  registry: "office-for-national-statistics"
  copyright: "Contains National Statistics data © [Crown copyright and database right\
    \ 2013](http://www.nationalarchives.gov.uk/doc/open-government-licence/),\n Contains\
    \ Ordnance Survey data © [Crown copyright and database right 2013](http://www.ordnancesurvey.co.uk/oswebsite/docs/licences/os-opendata-licence.pdf),\n\
    \ Contains Royal Mail data © [Royal Mail copyright and database right 2013](http://www.dfpni.gov.uk/lps/index/copyright_licensing_publishing.htm)"
food-premises-rating:
  entry-number: "6"
  item-hash: "sha-256:75eb4b008d76bbc3ca0fe6521af31cf98a78e87880c19d2cb759db9be9ad9b20"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Food hygiene inspection ratings"
  phase: "alpha"
  fields:
  - "food-premises-rating"
  - "food-premises"
  - "food-premises-rating-value"
  - "food-premises-rating-hygiene-score"
  - "food-premises-rating-structural-score"
  - "food-premises-rating-confidence-in-management-score"
  - "local-authority"
  - "food-premises-rating-reply"
  - "start-date"
  - "inspector"
  - "end-date"
  register: "food-premises-rating"
  registry: "food-standards-agency"
industry:
  entry-number: "10"
  item-hash: "sha-256:28778974f090f34e1c4074efd7d68d0857065598ff58318f7d23daf41fd70f47"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Standard Industry Codes (SIC) used to classify business establishments and\
    \ other standard units by the type of economic activity in which they are engaged"
  phase: "alpha"
  fields:
  - "industry"
  - "name"
  - "start-date"
  - "end-date"
  register: "industry"
  registry: "office-for-national-statistics"
local-authority:
  entry-number: "11"
  item-hash: "sha-256:ff002a99a88fc267c665e6ff65a60a7bf667982a98af03e154b64545a6e57d48"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Local authorities in England"
  phase: "alpha"
  fields:
  - "local-authority"
  - "name"
  - "website"
  - "email"
  - "address"
  - "start-date"
  - "end-date"
  register: "local-authority"
  registry: "department-for-communities-and-local-government"
public-body:
  entry-number: "15"
  item-hash: "sha-256:af73462e95fbcc4da50e81e0f1f1006e0c52d433728eff0a406bfc7e53ad5358"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Ministerial Departments and agencies sponsored by HM Government"
  phase: "alpha"
  fields:
  - "public-body"
  - "name"
  - "website"
  - "public-body-type"
  - "parent-bodies"
  - "text"
  - "crest"
  - "official-colour"
  register: "public-body"
  registry: "cabinet-office"
field:
  entry-number: "5"
  item-hash: "sha-256:e744c984158aea29904201aee263815a4bdab401ff8e6a194b25ff640ce191e2"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Field names which may appear in a register"
  phase: "alpha"
  fields:
  - "field"
  - "datatype"
  - "phase"
  - "register"
  - "cardinality"
  - "text"
  register: "field"
  registry: "cabinet-office"
food-premises-type:
  entry-number: "7"
  item-hash: "sha-256:3b852accf3e75e8843f3e108afbc2790b1941cd256edb07ea4c5a02f407d0934"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Types of premises which prepare and serve food"
  phase: "alpha"
  fields:
  - "food-premises-type"
  - "name"
  register: "food-premises-type"
  registry: "food-standards-agency"
datatype:
  entry-number: "4"
  item-hash: "sha-256:cea542d4693791ae2936b8432997f5ea19f42b6a6e9403de0c9cfdc200b06e58"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Datatypes constraining values used by register fields and idenitifying ways\
    \ in which it may be encoded a representation"
  phase: "alpha"
  fields:
  - "datatype"
  - "phase"
  - "text"
  register: "datatype"
  registry: "cabinet-office"
school:
  entry-number: "18"
  item-hash: "sha-256:1e7aa55e22668057e21c4de7f7c897c50a244af814a5b682757316631b63b771"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Primary, secondary and special needs schools in England and Wales"
  phase: "alpha"
  fields:
  - "school"
  - "name"
  - "start-date"
  - "end-date"
  - "gender"
  - "religious-character"
  - "minimum-age"
  - "maximum-age"
  - "headteacher"
  - "website"
  - "address"
  register: "school"
  registry: "department-for-education"
premises:
  entry-number: "14"
  item-hash: "sha-256:f0354e840c33aae88052c9fc2a27d2a00530108dc0a83da66b7b5fcb9146594e"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Commercial properties eligable for business rates in England and Wales"
  phase: "alpha"
  fields:
  - "premises"
  - "address"
  - "start-date"
  - "end-date"
  register: "premises"
  registry: "valuation-office-agency"
uk:
  entry-number: "20"
  item-hash: "sha-256:a3d2ed2304ef14b93980aaca84540dbabd9e3b5a720c4e316f2574e6e860a373"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "UK and Crown dependencies"
  phase: "alpha"
  fields:
  - "uk"
  - "name"
  - "official-name"
  - "start-date"
  - "end-date"
  - "citizen-names"
  - "text"
  register: "uk"
  registry: "cabinet-office"
company:
  entry-number: "2"
  item-hash: "sha-256:1aa74b7e97518cec76b5be02ddc43b99c8a83395b958a8ff4d9180b07899ec6f"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Companies in England and Wales"
  phase: "alpha"
  fields:
  - "company"
  - "name"
  - "company-status"
  - "registered-office"
  - "industry"
  - "start-date"
  - "end-date"
  register: "company"
  registry: "companies-house"
location:
  entry-number: "12"
  item-hash: "sha-256:91f0d2a1dc48d2a19e14a46d52f9e0fb530274f9d9e9e47edf693b78234dfcfc"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Geographic locations of places found in government data which may be published\
    \ under an open government licence"
  phase: "alpha"
  fields:
  - "location"
  - "point"
  register: "location"
  registry: "cabinet-office"
government-domain:
  entry-number: "9"
  item-hash: "sha-256:e0e4e95b810a50613af7cf447213b9f4760c6d77027b76136d3708c153995a83"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Internet domain names used by HM Government"
  phase: "alpha"
  fields:
  - "government-domain"
  - "owner"
  - "end-date"
  register: "government-domain"
  registry: "government-digital-service"
register:
  entry-number: "16"
  item-hash: "sha-256:a90a6cb96e09cb4a1136889d18c4f9bb0f0a8a80de87d0f947c2618c8724e067"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "Registers maintained by HM Government"
  phase: "alpha"
  fields:
  - "register"
  - "text"
  - "registry"
  - "phase"
  - "copyright"
  - "fields"
  register: "register"
  registry: "cabinet-office"
territory:
  entry-number: "19"
  item-hash: "sha-256:61939046094f24cb89897f0707fb6ab2cfb85af3d8dfe70bce5446e2de52cba1"
  entry-timestamp: "2016-04-21T10:14:21Z"
  text: "British English-language names and descriptive terms for territories"
  phase: "alpha"
  fields:
  - "territory"
  - "name"
  - "official-name"
  - "start-date"
  - "end-date"
  - "citizen-names"
  - "text"
  register: "territory"
  registry: "foreign-commonwealth-office"

